-- Banco de dados do Quadro da Obra de Deus
-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.members (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  missa_dia text,
  domingo text,
  segunda text,
  terca text,
  quarta text,
  quinta text,
  sexta text,
  sabado text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.change_log (
  id bigint generated by default as identity primary key,
  member_id uuid references public.members(id) on delete set null,
  member_name text not null,
  old_data jsonb,
  new_data jsonb,
  changed_at timestamptz not null default now()
);

alter table public.members enable row level security;
alter table public.change_log enable row level security;

-- Para a primeira versão, a leitura pública é permitida.
-- A edição deve ser protegida pelo login da aplicação.
create policy "public read active members"
on public.members for select
using (active = true);

create policy "public insert members"
on public.members for insert
with check (true);

create policy "public update members"
on public.members for update
using (true)
with check (true);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists members_updated_at on public.members;
create trigger members_updated_at
before update on public.members
for each row execute function public.set_updated_at();

-- Dados iniciais do último quadro conhecido.
insert into public.members
(name, missa_dia, domingo, segunda, terca, quarta, quinta, sexta, sabado)
values
('Antonio Luiz','Quarta-feira','Laudes','Terça','Sexta','Nona','Nona','Vésperas','Completas'),
('Carlos Albergoni','Sexta-feira','Laudes','Ofício das Leituras','Terça','Completas','Vésperas','Nona','Sexta'),
('Danilo Gomes Rosa','Sábado','Ofício das Leituras','Laudes','Terça','Sexta','Nona','Vésperas','Completas'),
('David Vieira','Sábado','Ofício das Leituras','Laudes','Terça','Sexta','Nona','Vésperas','Completas'),
('Felipe Menezes Soares','Sábado','Completas','Ofício das Leituras','Laudes','Terça','Sexta','Nona','Vésperas'),
('Gabriel Viana Gomes','Sábado','Completas','Laudes','Terça','Sexta','Nona','Vésperas','Ofício das Leituras'),
('João Gabriel Buso Torro','Sexta-feira','Terça','Sexta','Nona','Vésperas','Ofício das Leituras','Completas','Laudes'),
('João Pedro Duarte dos Santos','Quarta-feira','Sexta','Laudes','Terça','Vésperas','Completas','Ofício das Leituras','Nona'),
('Jônatas Matheus Lopes Brasileiro','Segunda-feira','Laudes','Terça','Sexta','Nona','Vésperas','Completas','Ofício das Leituras'),
('Josimar Rodrigues','Quinta-feira','Terça','Laudes','Vésperas','Completas','Vésperas','Sexta','Ofício das Leituras'),
('Junior Ricardo Martins','Quinta-feira','Completas','Ofício das Leituras','Sexta','Nona','Nona','Vésperas','Terça'),
('Kelvin de Almeida Soares','Sábado','Ofício das Leituras','Laudes','Terça','Sexta','Nona','Vésperas','Ofício das Leituras'),
('Michel','Terça-feira','Completas','Laudes','Ofício das Leituras','Nona','Terça','Sexta','Vésperas'),
('Sandro Bueno de Paula','Terça-feira','Ofício das Leituras','Completas','Terça','Sexta','Nona','Terça','Laudes'),
('Vinícius Fernandes de Campos','Sábado','Laudes','Nona','Sexta','Vésperas','Completas','Terça','Ofício das Leituras'),
('Vinicius Batista da Costa','Sexta-feira','Nona','Vésperas','Completas','Ofício das Leituras','Sexta','Terça','Laudes'),
('Willian de Almeida','Quinta-feira','Completas','Ofício das Leituras','Laudes','Terça','Sexta','Nona','Vésperas')
on conflict (name) do update set
missa_dia=excluded.missa_dia,
domingo=excluded.domingo,
segunda=excluded.segunda,
terca=excluded.terca,
quarta=excluded.quarta,
quinta=excluded.quinta,
sexta=excluded.sexta,
sabado=excluded.sabado,
active=true,
updated_at=now();

-- Rafael não faz parte do quadro.
delete from public.members where lower(name) like '%rafael%';
